# 1.) Import the Credit Card Fraud Data From CCLE

In [3]:
import pandas as pd
from google.colab import drive
import matplotlib.pyplot as plt
import numpy as np

In [4]:
drive.mount('/content/gdrive/', force_remount = True)

Mounted at /content/gdrive/


In [5]:
df = pd.read_csv("/content/gdrive/MyDrive/Econ441B/fraudTest.csv")

In [6]:
df.columns

Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
       'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
       'merch_lat', 'merch_long', 'is_fraud'],
      dtype='object')

In [7]:
df.head()[:5]

Unnamed: 0 trans_date_trans_time            cc_num  \
0           0   2020-06-21 12:14:25  2291163933867244   
1           1   2020-06-21 12:14:33  3573030041201292   
2           2   2020-06-21 12:14:53  3598215285024754   
3           3   2020-06-21 12:15:15  3591919803438423   
4           4   2020-06-21 12:15:17  3526826139003047   

                               merchant        category    amt   first  \
0                 fraud_Kirlin and Sons   personal_care   2.86    Jeff   
1                  fraud_Sporer-Keebler   personal_care  29.84  Joanne   
2  fraud_Swaniawski, Nitzsche and Welch  health_fitness  41.28  Ashley   
3                     fraud_Haley Group        misc_pos  60.05   Brian   
4                 fraud_Johnston-Casper          travel   3.19  Nathan   

       last gender                       street  ...      lat      long  \
0   Elliott      M            351 Darlene Green  ...  33.9659  -80.9355   
1  Williams      F             3638 Marsh Union  ...  40.3207 -110.4360   
2     Lopez      F         9333 Valentine Point  ...  40.6729  -73.5365   
3  Williams      M  32941 Krystal Mill Apt. 552  ...  28.5697  -80.8191   
4    Massey      M     5783 Evan Roads Apt. 465  ...  44.2529  -85.0170   

   city_pop                     job         dob  \
0    333497     Mechanical engineer  1968-03-19   
1       302  Sales professional, IT  1990-01-17   
2     34496       Librarian, public  1970-10-21   
3     54767            Set designer  1987-07-25   
4      1126      Furniture designer  1955-07-06   

                          trans_num   unix_time  merch_lat  merch_long  \
0  2da90c7d74bd46a0caf3777415b3ebd3  1371816865  33.986391  -81.200714   
1  324cc204407e99f51b0d6ca0055005e7  1371816873  39.450498 -109.960431   
2  c81755dbbbea9d5c77f094348a7579be  1371816893  40.495810  -74.196111   
3  2159175b9efe66dc301f149d3d5abf8c  1371816915  28.812398  -80.883061   
4  57ff021bd3f328f8738bb535c302a31b  1371816917  44.959148  -85.884734   

   is_fraud  
0         0  
1         0  
2         0  
3         0  
4         0  

[5 rows x 23 columns]

# 2.) Select four columns to use as features (one just be trans_date_trans)

In [8]:
df_select = df[["trans_date_trans_time","category","amt","city_pop","is_fraud"]]

In [9]:
df_select.head()

trans_date_trans_time        category    amt  city_pop  is_fraud
0   2020-06-21 12:14:25   personal_care   2.86    333497         0
1   2020-06-21 12:14:33   personal_care  29.84       302         0
2   2020-06-21 12:14:53  health_fitness  41.28     34496         0
3   2020-06-21 12:15:15        misc_pos  60.05     54767         0
4   2020-06-21 12:15:17          travel   3.19      1126         0

# 3.) Create a unique variable out of trans_date. Creat dummies for string variables

In [10]:
type(df["trans_date_trans_time"][0])

str

In [11]:
df["trans_date_trans_time"] = pd.to_datetime(df["trans_date_trans_time"])

In [12]:
type(df["trans_date_trans_time"][0])

pandas._libs.tslibs.timestamps.Timestamp

In [13]:
df_select["time_var"] = [i.second for i in df["trans_date_trans_time"]]

<ipython-input-13-855a9cbdedbb>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_select["time_var"] = [i.second for i in df["trans_date_trans_time"]]


In [14]:
df_select.head()

trans_date_trans_time        category    amt  city_pop  is_fraud  time_var
0   2020-06-21 12:14:25   personal_care   2.86    333497         0        25
1   2020-06-21 12:14:33   personal_care  29.84       302         0        33
2   2020-06-21 12:14:53  health_fitness  41.28     34496         0        53
3   2020-06-21 12:15:15        misc_pos  60.05     54767         0        15
4   2020-06-21 12:15:17          travel   3.19      1126         0        17

In [15]:
dummies = pd.get_dummies(df_select["category"])

In [16]:
X = pd.concat([dummies,df_select[["amt","city_pop","time_var"]]],axis =1)
y = df_select["is_fraud"]

In [17]:
X.head()

entertainment  food_dining  gas_transport  grocery_net  grocery_pos  \
0              0            0              0            0            0   
1              0            0              0            0            0   
2              0            0              0            0            0   
3              0            0              0            0            0   
4              0            0              0            0            0   

   health_fitness  home  kids_pets  misc_net  misc_pos  personal_care  \
0               0     0          0         0         0              1   
1               0     0          0         0         0              1   
2               1     0          0         0         0              0   
3               0     0          0         0         1              0   
4               0     0          0         0         0              0   

   shopping_net  shopping_pos  travel    amt  city_pop  time_var  
0             0             0       0   2.86    333497        25  
1             0             0       0  29.84       302        33  
2             0             0       0  41.28     34496        53  
3             0             0       0  60.05     54767        15  
4             0             0       1   3.19      1126        17

# 5.) Train a Logistic regression.

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

In [19]:
resample_X = X
resample_y = y
scaler = StandardScaler()
X_normalized = scaler.fit_transform(resample_X)

In [20]:
log_reg = LogisticRegression().fit(X_normalized, resample_y)

# 6.) The company you are working for wants to target at a False Positive rate of 5% what threshold should you use? (Use oversampled data)

In [21]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
import numpy as np

In [30]:
# predict class probabilities
y_prob = log_reg.predict_proba(resample_X)
y_prob

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:443: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


array([[1.00000000e+000, 0.00000000e+000],
       [1.00000000e+000, 4.12989997e-015],
       [1.00000000e+000, 0.00000000e+000],
       ...,
       [1.00000000e+000, 4.59417109e-187],
       [9.99999998e-001, 1.89298695e-009],
       [1.00000000e+000, 0.00000000e+000]])

In [31]:
# select the threshold that gives you the desired false negative percentage
target_fn_percentage = 5
threshold = np.percentile(y_prob[:,1],100-target_fn_percentage)

In [32]:
# make predictions using the selected threshold
y_pred = (y_prob[:,1]> threshold).astype(int)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [34]:
# calculate the confusion matrix
confusion_matrix(resample_y,y_pred)

array([[526377,  27197],
       [  1556,    589]])

# 7.) If the company makes .02*amt on True transactions and loses -amt on False (Use original data)

In [26]:
df_temp = df_select.copy()

In [27]:
df_temp["pred"] = log_reg.predict(resample_X)

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:443: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


In [28]:
df_temp = df_temp[["pred", "is_fraud", "amt"]]

In [29]:
df_temp.head()

pred  is_fraud    amt
0     0         0   2.86
1     0         0  29.84
2     0         0  41.28
3     0         0  60.05
4     0         0   3.19

In [39]:
a = 0
for row in df_temp.itertuples():
    if row.pred == 0:
      if row.is_fraud == 0:
        a += .02*(row.amt)
      elif row.is_fraud == 1:
        a += -1*(row.amt)
    else:
      continue
print(a)

-35132.44080000058


# 8.) Using Logistic Regression Lasso to inform you. Would you use the selected features in a trusted prediction model? 

In [40]:
from sklearn.linear_model import Lasso

lasso = Lasso().fit(resample_X, resample_y) 

In [44]:
lasso.coef_

array([-0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
        0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
        0.00000000e+00, -0.00000000e+00, -0.00000000e+00,  0.00000000e+00,
        0.00000000e+00, -0.00000000e+00,  3.14081157e-05, -1.04761571e-09,
        0.00000000e+00])

Hence, we can find that most of our variable coefficients go to 0, which means that the selected features do not work really well.